site_name: DashPad Documentation (WIP)
site_url: https://dashpad.neal.media
site_description: Modular system monitoring solution for repurposing tablets as dedicated monitoring displays (work-in-progress)

repo_name: mrchrisneal/DashPad
repo_url: https://github.com/mrchrisneal/DashPad
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Architecture: architecture.md
  - DashPad-API:
    - Overview: api/index.md
    - Configuration: api/configuration.md
    - Endpoints: api/endpoints.md
    - Modules: api/modules.md
  - DashPad-Web:
    - Overview: web/index.md
    - Quick Start: web/quick-start.md
    - Configuration: web/configuration.md
    - Usage: web/usage.md
    - Troubleshooting: web/troubleshooting.md
    - Deployment:
      - Google Cloud Run: web/deployment/cloud-run.md
  - FAQ: faq.md
  - Devlog: devlog/index.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - section-index
  - blog:
      blog_dir: devlog
      blog_toc: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: true
      caption_position: bottom
      background: #1e2129
      shadow: false
      manual: false
  - document-dates:
      position: top            # Display position: top (after title)  bottom (end of document), default: bottom
      type: timeago               # Date type: date  datetime  timeago, default: date
      locale: en               # Localization: en zh zh_TW es fr de ar ja ko ru, default: en
      date_format: '%Y-%m-%d'  # Date format strings, e.g., %Y-%m-%d, %b %d, %Y, etc
      time_format: '%H:%M:%S'  # Time format strings (valid only if type=datetime)
      exclude: # List of excluded files
        - index.md              # Exclude specific file
        - devlog/index.md
        - private/*            # Exclude all files in private directory, including subdirectories
      show_author: false        # Show author or not, default: true

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mrchrisneal/DashPad
  analytics:
    provider: google
    property: G-LQ4QTFY855

copyright: Copyright &copy; 2025 Chris Neal